### ISSUE TITLE
how to train old owod split?

### ISSUE THREAD

**Issue by xiaomabufei** [akshitac8/OW-DETR#14]
how to train old owod split?

**Comment by akshitac8** [comment]
Hello @xiaomabufei I have uploaded the config file for the same. Please let me know if any other confusion persist.

**Comment by xiaomabufei** [comment]
could you share your incremental experiment spilt?

**Comment by akshitac8** [comment]
Hello @xiaomabufei we follow the same split as the OWOD paper.

**Comment by xiaomabufei** [comment]
the OWOD paper also do not share their split. How you follow it?

**Comment by xiaomabufei** [comment]
@akshitac8
