### ISSUE TITLE
Problems of OWOD proposed splits in Task 1

### ISSUE THREAD

**Issue by Wang0203** [akshitac8/OW-DETR#15]
Hello, when training with OWOD proposed splits, why are there 5  '0.0'  in AP50?
**Task 1**
"AP50 ": "['64.0', '32.8', '30.0', '26.5', '57.1', '38.1', '78.3', '43.1', '60.7', '45.9', '46.3', '42.9', '69.9', **_'0.0', '0.0', '0.0', '0.0', '0.0'_**, '54.3', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.3']"
![owod](https://user-images.githubusercontent.com/65695245/179387991-6c6c7127-15cf-47af-95f4-7b08f0f2362e.png)

**Comment by akshitac8** [comment]
Hello @Wang0203 Can you please share your final AP numbers as well?
