### ISSUE TITLE
The training schedule

### ISSUE THREAD

**Issue by luckychay** [akshitac8/OW-DETR#17]
Dear Author,

In the paper, I see that every task is trained for 50 epochs and finetuned for 20 epochs as 
![13291a30151dcbb1fe48d3092ce85ce](https://user-images.githubusercontent.com/55084546/181871005-c006ec41-bffc-4847-a365-799907abcf43.jpg)

However, in `configs/OWOD_new_split.sh`, I see the training schedule is following a different setting as highlighted by the red boxes.
![e2489ae780a580596b7bbb8e7fb1c3a](https://user-images.githubusercontent.com/55084546/181871072-0e206be4-2334-4e2e-9713-eb023ee1c85c.png)

Is there anything I missed? Looking forward to your reply. Thanks.

**Comment by orrzohar-stanford** [comment]
I actually trained using their scripts but could not recreate their results. For T1, AP50 only reached 9.4 while unknown recall reached 5.97

**Comment by luckychay** [comment]
Yeah, I did notice that they continue numbering the epochs across tasks. But even though in that case, theirs scripts are apparently different from what discribed in the paper.

**Comment by akshitac8** [comment]
Hello @luckychay @orrzohar-stanford The paper use 2 open-world splits and I have updated the repo with both splits configs. Can you please let me know which split config is causing the problem?

**Comment by orrzohar-stanford** [comment]
Dear authors,
Thank you for responding! I have been using the new proposed data splits. After training the model for 40 epochs + 10 fine-tuning, I am getting results closer to what was reported - but still a little off. I am not sure why - I used the (unmodified) bash scripts provided (trained on a similar machine with 8 V100 GPUs/etc). Any reason you can think of?


<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>




Task IDs | Task 1 |  
-- | -- | --
  | U-Recall | mAP
ORE-EBUI | 1.5 | 61.4
Ours: OW-DETR | 5.7 | 71.5
Original codebase | 3.9 | 71.85
Amended (40+10) | 5.05 | 71.9


</body>

</html>


And overall:
![image](https://user-images.githubusercontent.com/91989868/183202586-0643880e-7923-422f-a277-1de63f6dae5e.png)

**Comment by luckychay** [comment]
> Hello @luckychay @orrzohar-stanford The paper use 2 open-world splits and I have updated the repo with both splits configs. Can you please let me know which split config is causing the problem?

Thanks for your reply. I am using old splits from ORE, in fact no problem is causing by the config for me. I am just confused about how many epochs I should train and finetune in incremental step. I notice that your newly uploaded scripts train about 5 epochs for task2,3,4 and finetune 45,30,20 epochs respectivly. The training epochs is much less than 50 epochs. How could that happen?

I am not familiar with this part and thank you for your patience.

**Comment by Went-Liang** [comment]
> Dear authors, Thank you for responding! I have been using the new proposed data splits. After training the model for 40 epochs + 10 fine-tuning, I am getting results closer to what was reported - but still a little off. I am not sure why - I used the (unmodified) bash scripts provided (trained on a similar machine with 8 V100 GPUs/etc). Any reason you can think of?
> 
> <style> </style>
> Task IDs	Task 1	 
>  	U-Recall	mAP
> ORE-EBUI	1.5	61.4
> Ours: OW-DETR	5.7	71.5
> Original codebase	3.9	71.85
> Amended (40+10)	5.05	71.9
> And overall: ![image](https://user-images.githubusercontent.com/91989868/183202586-0643880e-7923-422f-a277-1de63f6dae5e.png)

Hello, could you share your trained models?

**Comment by akshitac8** [comment]
The weights are uploaded in the repository. According to the results you have shared they look pretty close so it just might be environment change or because of machine changes but you can always visualize and check how the unknown classes are responding to your code.

**Comment by zhongxiangzju** [comment]
Dear @akshitac8 and @orrzohar-stanford,

May I ask that how long it takes to train the model on OWOD_split_task1 using 8 V100 GPUs for 50 epoches ? I only have 2 RTX3090 GPUs, and I am estimating if it is possible and how long it may take to train the models.

Thanks.
