### ISSUE TITLE
about the backbone "DINO resnet50" and do IL

### ISSUE THREAD

**Issue by Force-wyz** [akshitac8/OW-DETR#2]
code 
`            print("DINO resnet50")
            backbone = resnet50(pretrained=False, replace_stride_with_dilation=[False, False, dilation], norm_layer=norm_layer)
            if is_main_process():
                state_dict = torch.load("/proj/cvl/users/x_fahkh/akshita/Deformable-DETR/models/dino_resnet50_pretrain/dino_resnet50_pretrain.pth")
                backbone.load_state_dict(state_dict, strict=False)
`
in backbone.py  
I want to know how to get this pretrained model? use ImageNet or the first task's images?
and I would like to ask if you are not using any incremental training paradigm (e.g. knowledge distillation) because I don't see the relevant part in the code.
Thank you for such an excellent work.

**Comment by akshitac8** [comment]
Hello @Force-wyz Please download the DINO pretrained model from here -> https://dl.fbaipublicfiles.com/dino/dino_resnet50_pretrain/dino_resnet50_pretrain.pth
