### ISSUE TITLE
How to trian "19+1" , "15+5" and "10+10" settings?

### ISSUE THREAD

**Issue by Wang0203** [akshitac8/OW-DETR#20]
Hello! How to trian "19+1" , "15+5" and "10+10" settings?

**Comment by akshitac8** [comment]
Hello @Wang0203 we have followed the same training strategies as the OWOD paper.

**Comment by aooating** [comment]
> Hello! How to trian "19+1" , "15+5" and "10+10" settings?

Have you reproduced the results yet?
