### ISSUE TITLE
RuntimeError: CUDA out of memory, in t1_train task.

### ISSUE THREAD

**Issue by lianghrx** [akshitac8/OW-DETR#23]
Our gpu devices are RTX 2080TIs with only 11GB memory, but the training data requires 10-12GB GPU memory (as far as I know).

Is there any configuration to reduce the runtime memory requirements?

**Comment by akshitac8** [comment]
Please try with reducing the batch size and other hyper-parameters which can help you scale the code for RTX 2080.
