### ISSUE TITLE
where is requirement.txt

### ISSUE THREAD

**Issue by Arosy30** [akshitac8/OW-DETR#25]

**Comment by akshitac8** [comment]
Hello @Arosy30 the requirement.txt is mentioned in the readme which is similar to the original deformable detr readme.

**Comment by Arosy30** [comment]
Thanks for your reply and amazing work,I have run this work.And now when I change the number of batchsize,If I need change the number of iter too?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akshitac8/OW-DETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 上午7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akshitac8/OW-DETR] where is requirement.txt (Issue #25)





 
Closed #25 as completed.
