### ISSUE TITLE
how do you select K from M=200

### ISSUE THREAD

**Issue by luoyuchenmlcv** [akshitac8/OW-DETR#3]
In implementation details, you mentioned M=200, as the number of object queries. K from M for known object detection. From M-K object queries, the top k_u is set as 5 for detecting the pseudo-unknown objects, how do you set the number of K? Is K from the number of object-queries that the novel classifier output as non-zero, or it was empirically set as a fixed number?

**Comment by akshitac8** [comment]
Hello @luoyuchenmlcv sorry for the late response. For selecting k, we set that value empirically but keeping in mind that the classifier can learn the seperation between and known and unknowns.
