### ISSUE TITLE
Link to dataset is broken

### ISSUE THREAD

**Issue by zxyang521** [akshitac8/OW-DETR#4]
![image](https://user-images.githubusercontent.com/11439132/163188999-730efab7-e9d7-4671-b651-a9bb8a26fa78.png)

The link is broken, cannot download the dataset.

**Comment by akshitac8** [comment]
Hello @zxyang521. Thank you for pointing it out. I will be fixing it today.

**Comment by Wang0203** [comment]
Hello @akshitac8. This link is still broken, or are there other links?

**Comment by Wang0203** [comment]
> Hello @zxyang521. Thank you for pointing it out. I will be fixing it today.

When is today?  still ok man?

**Comment by akshitac8** [comment]
@zxyang521 the details for our proposed dataset has been added in the readme

**Comment by akshitac8** [comment]
Please re-open if error still persist.
