### ISSUE TITLE
NotImplementedError: Cuda is not availabel

### ISSUE THREAD

**Issue by YH-2023** [akshitac8/OW-DETR#49]
when i run the   sh ./make.sh
NotImplementedError: Cuda is not availabel

how can i solve it

**Comment by EdwardLeeLPZ** [comment]
> when i run the sh ./make.sh NotImplementedError: Cuda is not availabel
> 
> how can i solve it

Same for me

**Comment by YH-2023** [comment]
> 

cuda is not installed on your server, you need to install cuda
