### ISSUE TITLE
iOD

### ISSUE THREAD

**Issue by aooating** [akshitac8/OW-DETR#6]
What is the upper bound on the iOD mission of PASCAL VOC? Have you tested it?

**Comment by akshitac8** [comment]
We didn't test the upper-bound of OW-DETR of pascal voc for IOD.

**Comment by akshitac8** [comment]
The network of IOD is same as OW-DETR and yes pseudo-unknown is needed.

**Comment by aooating** [comment]
Ok, thank you very much for your reply!
