### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Innary** [akshitac8/OW-DETR#7]
thank you for your code,but I ran into some problems.

1.  No such file or directory: '<dir>/OW-DETR/data/OWDETR/VOC2007/ImageSets/t4_ft_new_split.txt
2. FileNotFoundError: [Errno 2] No such file or directory: '/proj/cvl/users/x_fahkh/akshita/Deformable-DETR/models/dino_resnet50_pretrain/dino_resnet50_pretrain.pth'
3. The link is still disabled

I didn't find these in the code  or information you provided, can you please tell me where to find these files,thank you ~

**Comment by Innary** [comment]
4. The evaluation mode does not work, because in engine.py：
`coco_evaluator = OWEvaluator(base_ds, iou_types)` don't have parameter **args**

5.When eval:
```
traffic light has 566 predictions.
<dir>/OW-DETR/datasets/open_world_eval.py:407: RuntimeWarning
: invalid value encountered in true_divide
  rec = tp / float(npos)     
fire hydrant has 0 predictions.
```

**Comment by akshitac8** [comment]
Hello @Innary 
Can you please pull the latest commit and try again as I have made changes to the code.

**Comment by akshitac8** [comment]
Please re-open if the error still persist
